Swal.fire({
    title : '<b style="color:#FF4500;">¡Correcto!</b>',
    html:'<b style="color:black;">Estado del producto actualizado.</b>',
  //  icon: 'warning',
    confirmButtonText: '<a class="entendido" href="cambiar_estproducto.php">Entendido</a>',
    padding: '-1rem',
  //   backdrop: false,
   // grow: 'column',
    timer: '500000',
   // background:'#f2dede',
    timerProgressBar : true,
    toast : true,
    position : 'center-end',
    showConfirmButton : true,
    confirmButtonColor:'#F85D03',
    confirmButtonArialLabel: 'Confirmar',
   // stopKeydownPropagation: true,
    imageUrl: '../../Imagenes/kikeredondo1.png',
    imageWidth : '38px'
    });